### ISSUE TITLE
Shell Checker 

### ISSUE THREAD

**Issue by camlafit** [BoOz/spip_statique#2]
Salut

Je tombe sur divers problèmes de compatibilités sh/bash en autre.
J'ai passé un coup de shellchecker, PR en cours

**Comment by fhoogstoel** [comment]
Bonjour.
Le code semble compatible avec bash. Pas d'erreur avec #!/bin/bash au lieu de #!/bin/sh

**Comment by lpointal** [comment]
J'ai du passer le shebang vers bash, sinon erreur [[ inconnu.
A+
Laurent.

**Comment by BoOz** [comment]
Super ca https://www.shellcheck.net/

Sur Mac OS ou je l'utilise ça fonctionne tel quel mais apparemment `#!/bin/bash` serait plus adapté en effet.
